version: "3"

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      driver: none
    ports:
      - "5438:5432"
    networks:
      - breakdown-dev
    volumes:
      - breakdown-postgres-data:/var/lib/postgresql/data
  # app-service:
  #   networks:
  #     - breakdown-dev
  #   privileged: true
  #   volumes:
  #     - ./app-service:/app
  #   build:
  #     context: .
  #     dockerfile: ./app-service/Dockerfile.local
  #   ports:
  #     - 8080:8080
  #   environment:
  #     HMAC_KEY: ${HMAC_KEY}
  #     DATABASE_URL: ${DATABASE_URL}
  #     PROPUBLICA_API_KEY: ${PROPUBLICA_API_KEY}
  #   command: sh -c "cargo watch -x run"
  #   depends_on:
  #     - postgres

networks:
  breakdown-dev:
    driver: bridge
volumes:
  breakdown-postgres-data: {}
  bd-app-service-registry:
    driver: local
