version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      driver: none
    ports:
      - "5438:5432"
    networks:
      - breakdown-dev
    volumes:
      - breakdown-postgres-data:/var/lib/postgresql/data
  sync-service:
    networks:
      - breakdown-dev
    privileged: true
    volumes:
      - ./sync-service:/usr/src/app
      - bd-sync-service-registry:/root/.cargo/registry
    build:
      context: .
      dockerfile: ./sync-service/Dockerfile.local
    ports:
      - 8080:8080
    environment:
      HMAC_KEY: ${HMAC_KEY}
      DATABASE_URI: ${DATABASE_URI}
      PROPUBLICA_API_KEY: ${PROPUBLICA_API_KEY}
    depends_on:
      - postgres
    command: cargo watch -x run

networks:
  breakdown-dev:
    driver: bridge
volumes:
  breakdown-postgres-data: {}
  bd-sync-service-registry:
    driver: local
