version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      driver: none
    ports:
      - "5438:5432"
    networks:
      - breakdown-dev
    volumes:
      - breakdown-postgres-data:/var/lib/postgresql/data
  sync-service:
    networks:
      - breakdown-dev
    privileged: true
    volumes:
      - ./sync-service:/usr/src/app
      - bd-sync-service-registry:/root/.cargo/registry
    build:
      context: .
      dockerfile: ./sync-service/Dockerfile.local
    ports:
      - 8080:8080
    environment:
      NODE_ENV: ${NODE_ENV}
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_DB_URL: ${POSTGRES_DB_URL}
    depends_on:
      - postgres
    command: cargo watch -x run

networks:
  breakdown-dev:
    driver: bridge
volumes:
  breakdown-postgres-data: {}
  bd-sync-service-registry:
    driver: local
