version: "3"

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      driver: none
    ports:
      - "5438:5432"
    networks:
      - breakdown-dev
    volumes:
      - breakdown-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - breakdown-redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6378:6379"
    networks:
      - breakdown-dev
  meilisearch:
    image: getmeili/meilisearch:v1.7
    container_name: meilisearch
    restart: always
    ports:
      - 7700:7700
    volumes:
      - breakdown-meilisearch-data:/data.ms
    networks:
      - breakdown-dev
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
  app-service:
    networks:
      - breakdown-dev
    privileged: true
    volumes:
      - ./app-service/src:/app/src
    build:
      context: ./app-service
      dockerfile: ./Dockerfile.local
    command: yarn dev
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      NODE_ENV: local
      PORT: 8080
      REDIS_HOST: redis
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/postgres}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      TWILIO_ACCOUNT_ID: ${TWILIO_ACCOUNT_ID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      GEOCODIO_API_KEY: ${GEOCODIO_API_KEY}
      PROPUBLICA_API_KEY: ${PROPUBLICA_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_HOST: ${MEILI_HOST}
      CONGRESS_GOV_API_KEY: ${CONGRESS_GOV_API_KEY}

networks:
  breakdown-dev:
    driver: bridge
volumes:
  breakdown-postgres-data: {}
  breakdown-redis-data: {}
  breakdown-meilisearch-data: {}
