version: "3"

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      driver: none
    ports:
      - "5438:5432"
    networks:
      - breakdown-dev
    volumes:
      - breakdown-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - breakdown-redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6378:6379"
    networks:
      - breakdown-dev
  app-service:
    build:
      context: ./app-service
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    volumes:
      - ./app-service:/usr/src/app
    networks:
      - breakdown-dev
    links:
      - db
    environment:
      CARGO_INCREMENTAL: 1
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PROPUBLICA_API_KEY: ${PROPUBLICA_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
      HMAC_KEY: ${HMAC_KEY}
      DB_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      TWILIO_ACCOUNT_ID: ${TWILIO_ACCOUNT_ID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEOCODIO_API_KEY: ${GEOCODIO_API_KEY}
    command: bash -c "bash ./wait-for-it.sh postgres:5432 -q -- RUST_LOG=tower_http=trace cargo watch -x run"
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #       - 5672:5672
  #       - 15672:15672
  #   volumes:
  #       - breakdown-rabbitmq-data:/var/lib/rabbitmq/
  #       - breakdown-rabbitmq-data:/var/log/rabbitmq
  #   networks:
  #       - breakdown-dev
  # app-service:
  #   networks:
  #     - breakdown-dev
  #   privileged: true
  #   volumes:
  #     - ./app-service:/app
  #   build:
  #     context: .
  #     dockerfile: ./app-service/Dockerfile.local
  #   ports:
  #     - 8080:8080
  #   environment:
  #     HMAC_KEY: ${HMAC_KEY}
  #     DATABASE_URL: ${DATABASE_URL}
  #     PROPUBLICA_API_KEY: ${PROPUBLICA_API_KEY}
  #   command: sh -c "cargo watch -x run"
  #   depends_on:
  #     - postgres

networks:
  breakdown-dev:
    driver: bridge
volumes:
  breakdown-postgres-data: {}
  breakdown-redis-data: {}
  breakdown-rabbitmq-data: {}
  bd-app-service-registry:
    driver: local
