ALTER TABLE users
ADD COLUMN phone TEXT UNIQUE,
ADD COLUMN phone_verification_code INTEGER,
ADD COLUMN phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE,
ALTER COLUMN email DROP NOT NULL,
ALTER COLUMN password DROP NOT NULL;
