create table representatives
(
  id uuid  primary key  default uuid_generate_v1mc(),
  title  TEXT,
  short_title  TEXT,
  api_uri  TEXT,
  first_name  TEXT,
  middle_name  TEXT,
  last_name  TEXT,
  suffix  TEXT,
  date_of_birth  TEXT,
  gender  TEXT,
  party  TEXT,
  leadership_role  TEXT,
  twitter_account  TEXT,
  facebook_account  TEXT,
  youtube_account  TEXT,
  govtrack_id  TEXT,
  cspan_id  TEXT,
  votesmart_id  TEXT,
  icpsr_id  TEXT,
  crp_id  TEXT,
  google_entity_id  TEXT,
  fec_candidate_id  TEXT,
  url  TEXT,
  rss_url  TEXT,
  contact_form  TEXT,
  in_office  BOOLEAN,
  cook_pvi  TEXT,
  dw_nominate  NUMERIC(5, 2),
  seniority  TEXT,
  next_election  TEXT,
  total_votes  INTEGER,
  missed_votes  INTEGER,
  total_present  INTEGER,
  last_updated  TIMESTAMPTZ,
  ocd_id  TEXT,
  office  TEXT,
  phone  TEXT,
  fax  TEXT,
  state  TEXT,
  district TEXT,
  senate_class  TEXT,
  state_rank  TEXT,
  lis_id  TEXT,
  missed_votes_pct  NUMERIC(5, 2),
  votes_with_party_pct  NUMERIC(5, 2),
  votes_against_party_pct  NUMERIC(5, 2),
  -- Breakdown Fields
  propublica_id  TEXT UNIQUE NOT NULL,
  house TEXT NOT NULL,
  state_id uuid   CONSTRAINT fk_state REFERENCES states(id) ON UPDATE CASCADE ON DELETE SET NULL,
  district_id uuid   CONSTRAINT fk_district REFERENCES districts(id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at  TIMESTAMPTZ  NOT NULL  default now(),
  updated_at  TIMESTAMPTZ
);

SELECT trigger_updated_at('representatives');
