[package]
name = "breakdown-app-service"
version = "0.1.0"
authors = ["Ryan Oillataguerre <ryan@breakdown.us>"]
edition = "2021"
publish = false

[workspace]
members = [".", "api", "core", "entity", "migration"]

[dependencies]
app-service-api = { path = "api" }
