[package]
name = "sync-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.5" }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = "1.0.145"
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "postgres" ] }