name: Branch CI

on:
  push:
    paths:
      - "app-service/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # TODO: Swap this out for docker build?
      - uses: actions/checkout@v3
      - name: Build
        working-directory: app-service
        run: cargo build --verbose
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        working-directory: app-service
        run: cargo test --verbose
